name: Deploy to GitHub Pages
on:
  push:
    branches: [ master ]  # 你的主分支名，通常是main或master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy static_dist to Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./static_dist  # 你的静态文件目录
